name: map_containers
description: Map Containers

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 0.5.0
  cloud_firestore: 0.14.0+2

  firebase_analytics: 6.0.0
  firebase_crashlytics: 0.1.4+1

  rxdart: ^0.24.1
  geoflutterfire: ^2.2.1
  location: 3.0.2
  google_maps_flutter: 0.5.31

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
